### ISSUE TITLE
Undefined function resolve_fragment

### ISSUE THREAD

**Issue by cassiobock** [thephpleague/json-reference#22]
I'm having seeing this error `Fatal error: Uncaught Error: Call to undefined function League\JsonReference\resolve_fragment() ` when I try to dereference a JSON file.

I created a class with the following content:
``` php
<?php

namespace Swagger;

class Swagger
{
    public static function dereference()
    {
        $dereferencer  = new \League\JsonReference\Dereferencer();

        $schema = $dereferencer->dereference('file://' . __DIR__ . '/swagger.json');
    }
}
```

It seems like the `functions.php` is not being loaded with the Dereferencer class. Is there any extra configuration besides adding the reference on composer.json?

**Comment by matt-allan** [comment]
Hello,

What version of the library do you have installed (composer show league/json-reference)?  Are you using composer's autoloader (`vendor/autoload.php`)?

You shouldn't need to do anything except for include the composer autoloader which handles PSR-4 autoloading the classes and requiring `functions.php`.

**Comment by cassiobock** [comment]
Hi @yuloh 

The `vendor/autoload.php` solved the issue. I wasn't aware that it was required to load the `functions.php`.

Thanks
