### ISSUE TITLE
Full path in invalid pointer error message

### ISSUE THREAD

**Issue by mlambley** [thephpleague/json-reference#24]
Good day,

The cut-down version of my json is as follows:

```
{
    "swagger": "2.0",
    "definitions": {
        "MyEntity": {
            "GET_Entity": {
                "type": "object",
                "properties": {
                    "Id": {
                        "$ref": "#/definitions/MyEntity/Get.Id"
                    }
                }
            }
        }
    }
}
```

I am dereferencing it with the following:

```
$dereferencer = new League\JsonReference\Dereferencer();
$dereferencer->setReferenceSerializer(new \League\JsonReference\ReferenceSerializer\InlineReferenceSerializer());
$schema = $dereferencer->dereference('file:///' . str_replace('\\', '/', __DIR__) . '/test.json');
$fp = fopen(__DIR__ . '\\' . $resolvedName, 'wb');
fwrite($fp, json_encode($schema, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
fclose($fp);
```

I expect to see an error because I have not defined #/definitions/MyEntity/Get.Id. The error message is:

```
Uncaught League\JsonReference\Pointer\InvalidPointerException: The pointer referenced a value that does not exist.  The value was: "Get.Id"
```

Unfortunately this message is not helpful, because in my actual json I have several Get.Id in different namespaces. But, if I go into Pointer.php in the get function and pass $pointer to the exception constructor instead of $value->getValue(), I get the following error message:

```
Uncaught League\JsonReference\Pointer\InvalidPointerException: The pointer referenced a value that does not exist.  The value was: "/definitions/MyEntity/Get.Id"
```

Which is much better for me. I'll make a PR for this change, unless this change would introduce side-effects which I haven't considered?

Windows 10, PHP7, json-reference 1.1.0

Thank you.

**Comment by matt-allan** [comment]
HI,

Thanks for the detailed issue.  Returning the full pointer in the message sounds like a great idea to me.  The idea behind the 'value' in the current message was to let you know what part of the path was invalid.  That is pretty helpful for tracking down issues so maybe return both?

```
Uncaught League\JsonReference\Pointer\InvalidPointerException: The pointer "/definitions/MyEntity/Get.Id" referenced a value "Get.Id" that does not exist.
```

**Comment by mlambley** [comment]
Forgive my tardiness in addressing this issue. I am having troubles setting up the test suite on my windows environment.

I have isolated the culprit:
```
<?php
include './vendor/autoload.php';
use Sabre\Uri;

$id = 'circular-ext-ref.json';
$parentScope = 'file:///C:/Repos/json-reference/tests/fixtures/circular-ext-ref.json';

var_dump(Uri\resolve($parentScope, $id));
//string(67) "file://C:/Repos/json-reference/tests/fixtures/circular-ext-ref.json"
```

Which is wrong. It needs to be file:/// so that C: doesn't get interpreted as host:port.
I'll work around this for the time being, then submit a issue to the sabre people.

**Comment by mlambley** [comment]
Thank you!
