### ISSUE TITLE
Documentation pages say "JSON Guard"

### ISSUE THREAD

**Issue by fireproofsocks** [thephpleague/json-reference#5]
I don't know if it's supposed to be that way, but the documentation pages (e.g. http://json-guard.thephpleague.com/json-reference/dereferencing) all use the title of "JSON Guard".  It's confusing because one might think that they landed on the wrong page.  If the Dereferencer is part of the JSON Guard project, it would be best to indicate that in the link before sending the user to the docs.  Thanks!

**Comment by matt-allan** [comment]
Yeah, I should probably split the docs up.  json-reference started out as a component of json-guard but at this point they don't depend on each other at all.

**Comment by matt-allan** [comment]
New docs are up at http://json-reference.thephpleague.com/.  Thanks!
